# Generated by Django 3.0.2 on 2020-01-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191029_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank='true', max_length=50, null='true'),
            preserve_default='true',
        ),
    ]
